version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ubuntu/app.js
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 120
      runas: root
    - location: script/start_server.sh
      timeout: 120
      runas: root
