version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
